version: 2.1

jobs:
  preparation:
    machine:
      image: ubuntu-2204:current
    steps:
      - run:
          name: Preparation
          command: sudo apt update && sudo apt install -qqy libboost-dev libboost-filesystem-dev libsqlite3-dev libgtest-dev
      - checkout

  build:
    machine:
      image: ubuntu-2204:current
    environment:
      BUILD_TYPE: Release
    steps:
      - run:
          name: Configure cmake
          command: cmake -B ${CIRCLE_WORKING_DIRECTORY}/build -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
      - run:
          name: Build
          command: cmake --build ${CIRCLE_WORKING_DIRECTORY}/build --config ${BUILD_TYPE}

  test:
    machine:
      image: ubuntu-2204:current
    steps:
      - run:
          name: Run Unit tests
          command: ctest -C ${BUILD_TYPE}
          working_directory: ${CIRCLE_WORKING_DIRECTORY}/build

workflows:
  Build-and-test:
    jobs:
      - preparation
      - build:
          requires:
            - preparation
      - test:
          requires:
            - build
