
if (ENABLE_SQLITE_AMALGAMATION)
    add_definitions(-DEMBED_MSQLITECPP)
    add_definitions(-DBUILD_MSQLITECPP)
else (ENABLE_SQLITE_AMALGAMATION)
    set (SQLITE_LIB sqlite3)
    add_definitions(-DBUILD_MSQLITECPP)
endif (ENABLE_SQLITE_AMALGAMATION)

if (ENABLE_CODECOVERAGE)
    set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} --coverage")
    set (CMAKE_C_FLAGS "${CMAKE_C_FLAGS} --coverage")
endif (ENABLE_CODECOVERAGE)

if (APPLE)
    set(CMAKE_MACOSX_RPATH ON)
endif (APPLE)
