
set(CMAKE_CXX_STANDARD 14)

if (ENABLE_SQLITE_AMALGAMATION)
    set (LINK_SHARED STATIC)
    add_definitions(-DEMBED_MSQLITECPP)
    add_definitions(-DBUILD_MSQLITECPP)
else (ENABLE_SQLITE_AMALGAMATION)
    set (SQLITE_LIB sqlite3)
    add_definitions(-DBUILD_MSQLITECPP)
    set (LINK_SHARED SHARED)
endif (ENABLE_SQLITE_AMALGAMATION)

if (ENABLE_CODECOVERAGE)
    set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} --coverage")
    set (CMAKE_C_FLAGS "${CMAKE_C_FLAGS} --coverage")
endif (ENABLE_CODECOVERAGE)
