name: Package Debian

on:
  push:
    tags:
      - '**'    # triggers on ANY tag including hierarchical ones like stable/v2

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: jtdor/build-deb-action@v1
        id: package
        with:
          buildpackage-opts: --build=binary --no-sign

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "debian/artifacts/*"
          allowUpdates: true

